import { createHash } from 'node:crypto';
import { db } from '@researchflow/database';
import { cleanText } from '../api';
import { embeddingProvider } from './embedding-provider';
import { AIServiceError } from '../ai/types';

const MAX_UNIT_LENGTH = 12_000;
const SOURCE_THRESHOLD = Number(process.env.SIMILAR_SOURCE_THRESHOLD || 0.82);
const FINDING_THRESHOLD = Number(process.env.SIMILAR_FINDING_THRESHOLD || 0.84);
const MAX_COMPARISONS = Number(process.env.MAX_INTELLIGENCE_COMPARISONS || 20);
type Unit = { entityType: 'SOURCE'|'RESEARCH_ITEM'|'SUMMARY'|'FINDING'; entityKey: string; text: string; researchItemId?: string; analysisId?: string };
const asFindings = (value: unknown) => Array.isArray(value) ? value.filter((item): item is { finding: string; importance: string } => typeof item === 'object' && item !== null && typeof (item as { finding?: unknown }).finding === 'string') : [];
function vectorLiteral(vector: number[]) { return `[${vector.join(',')}]`; }
function units(source: { id: string; items: Array<{ id: string; content: string }>; analyses: Array<{ id: string; researchItemId: string; summary: string|null; keyFindings: unknown }> }): Unit[] { const result: Unit[] = []; const sourceText = cleanText(source.items.map((item) => item.content).join('\n\n'), MAX_UNIT_LENGTH); if (sourceText.length >= 120) result.push({ entityType: 'SOURCE', entityKey: source.id, text: sourceText }); for (const item of source.items) { const text = cleanText(item.content, MAX_UNIT_LENGTH); if (text.length >= 120) result.push({ entityType: 'RESEARCH_ITEM', entityKey: item.id, text, researchItemId: item.id }); } for (const analysis of source.analyses) { if (analysis.summary) result.push({ entityType: 'SUMMARY', entityKey: analysis.id, text: cleanText(analysis.summary, MAX_UNIT_LENGTH), researchItemId: analysis.researchItemId, analysisId: analysis.id }); asFindings(analysis.keyFindings).forEach((finding, index) => result.push({ entityType: 'FINDING', entityKey: `${analysis.id}:${index}`, text: cleanText(finding.finding, MAX_UNIT_LENGTH), researchItemId: analysis.researchItemId, analysisId: analysis.id })); } return result; }
export async function embedSource(userId: string, sourceId: string) { const source = await db.source.findFirst({ where: { id: sourceId, project: { userId } }, include: { items: true, analyses: { where: { status: 'COMPLETED' }, orderBy: { createdAt: 'desc' }, take: 1 } } }); if (!source) throw new AIServiceError('PROVIDER_UNAVAILABLE', 'Source not found.'); const provider = embeddingProvider(); const result = []; for (const unit of units(source)) { const contentHash = createHash('sha256').update(unit.text).digest('hex'); const existing = await db.embedding.findUnique({ where: { entityType_entityKey_contentHash: { entityType: unit.entityType, entityKey: unit.entityKey, contentHash } } }); if (existing?.status === 'COMPLETED') { result.push(existing); continue; } const row = await db.embedding.upsert({ where: { entityType_entityKey_contentHash: { entityType: unit.entityType, entityKey: unit.entityKey, contentHash } }, update: { userId, projectId: source.projectId, sourceId, researchItemId: unit.researchItemId, analysisId: unit.analysisId, contentPreview: unit.text.slice(0, 500), provider: provider.name, model: provider.model, dimensions: provider.dimensions, status: 'PROCESSING', errorMessage: null, attemptCount: { increment: 1 } }, create: { userId, projectId: source.projectId, sourceId, researchItemId: unit.researchItemId, analysisId: unit.analysisId, entityType: unit.entityType, entityKey: unit.entityKey, contentHash, contentPreview: unit.text.slice(0, 500), provider: provider.name, model: provider.model, dimensions: provider.dimensions, status: 'PROCESSING', attemptCount: 1 } }); try { const vector = await provider.generateEmbedding(unit.text); await db.$executeRawUnsafe('UPDATE "Embedding" SET "vector" = $1::vector, "status" = \'COMPLETED\', "errorMessage" = NULL, "updatedAt" = NOW() WHERE "id" = $2', vectorLiteral(vector), row.id); result.push({ ...row, status: 'COMPLETED' as const }); } catch (error) { const safe = error instanceof AIServiceError ? error : new AIServiceError('PROVIDER_UNAVAILABLE', 'Embedding generation failed.', true); await db.embedding.update({ where: { id: row.id }, data: { status: 'FAILED', errorMessage: safe.message } }); throw safe; } } await detectSimilarSources(userId, source.projectId, sourceId); return result; }
export async function semanticSearch(userId: string, query: string, projectId?: string, limit = 20) { const normalized = cleanText(query, 500); if (normalized.length < 3) throw new AIServiceError('EMPTY_CONTENT', 'Search query must contain at least 3 readable characters.'); const provider = embeddingProvider(); const vector = await provider.generateEmbedding(normalized); const bounded = Math.min(Math.max(limit, 1), 50); const rows = (await db.$queryRawUnsafe('SELECT e."id", e."sourceId", e."entityType", e."entityKey", e."contentPreview", s."title", s."url", s."projectId", (1 - (e."vector" <=> $1::vector))::float8 AS similarity FROM "Embedding" e JOIN "Source" s ON s."id" = e."sourceId" WHERE e."userId" = $2 AND ($3::text IS NULL OR e."projectId" = $3) AND e."status" = \'COMPLETED\' AND e."vector" IS NOT NULL ORDER BY (1 - (e."vector" <=> $1::vector)) DESC LIMIT $4', vectorLiteral(vector), userId, projectId ?? null, bounded)) as Array<{ id: string; sourceId: string; entityType: string; entityKey: string; contentPreview: string; title: string|null; url: string; projectId: string; similarity: number }>; return rows.map((row: any) => ({ ...row, relevance: Number((row.similarity * 0.8 + (row.contentPreview.toLowerCase().includes(normalized.toLowerCase()) ? 0.2 : 0)).toFixed(4)) })); }
export async function detectSimilarSources(userId: string, projectId: string, sourceId: string) { const row = (await db.$queryRawUnsafe('SELECT e1."sourceId", e2."sourceId" AS "targetSourceId", MAX((1 - (e1."vector" <=> e2."vector"))::float8) AS similarity FROM "Embedding" e1 JOIN "Embedding" e2 ON e1."entityType" = e2."entityType" AND e1."entityType" IN (\'SOURCE\', \'SUMMARY\', \'RESEARCH_ITEM\') AND e1."sourceId" <> e2."sourceId" WHERE e1."userId" = $1 AND e1."projectId" = $2 AND e1."sourceId" = $3 AND e2."status" = \'COMPLETED\' AND e1."status" = \'COMPLETED\' AND e1."vector" IS NOT NULL AND e2."vector" IS NOT NULL GROUP BY e1."sourceId", e2."sourceId" HAVING MAX(1 - (e1."vector" <=> e2."vector")) >= $4 ORDER BY similarity DESC LIMIT $5', userId, projectId, sourceId, SOURCE_THRESHOLD, MAX_COMPARISONS)) as Array<{ sourceId: string; targetSourceId: string; similarity: number }>; if (row.length) await db.researchRelationship.createMany({ data: row.flatMap((item: any) => [{ userId, projectId, sourceId, targetSourceId: item.targetSourceId, sourceEntity: 'SOURCE' as const, sourceEntityKey: item.sourceId, targetEntity: 'SOURCE' as const, targetEntityKey: item.targetSourceId, type: 'SIMILAR' as const, confidence: item.similarity, explanation: item.similarity >= 0.9 ? 'Highly similar semantic content.' : 'Possibly related semantic content.' }, { userId, projectId, sourceId: item.targetSourceId, targetSourceId: item.sourceId, sourceEntity: 'SOURCE' as const, sourceEntityKey: item.targetSourceId, targetEntity: 'SOURCE' as const, targetEntityKey: item.sourceId, type: 'SIMILAR' as const, confidence: item.similarity, explanation: item.similarity >= 0.9 ? 'Highly similar semantic content.' : 'Possibly related semantic content.' }]), skipDuplicates: true }); return row; }
export async function similarFindings(userId: string, findingId: string, limit = 10) { const [analysisId, index] = findingId.split(':'); if (!analysisId || index === undefined) throw new AIServiceError('EMPTY_CONTENT', 'Invalid finding identifier.'); const source = await db.aIAnalysis.findFirst({ where: { id: analysisId, source: { project: { userId } } }, select: { id: true } }); if (!source) throw new AIServiceError('PROVIDER_UNAVAILABLE', 'Finding not found.'); const target = await db.embedding.findFirst({ where: { userId, entityType: 'FINDING', entityKey: findingId, status: 'COMPLETED' } }); if (!target) throw new AIServiceError('EMPTY_CONTENT', 'This finding has no completed embedding.'); return (await db.$queryRawUnsafe('SELECT e."sourceId", e."entityKey", e."contentPreview", s."url", s."title", (1 - (e."vector" <=> (SELECT "vector" FROM "Embedding" WHERE "id" = $1)))::float8 AS similarity FROM "Embedding" e JOIN "Source" s ON s."id" = e."sourceId" WHERE e."userId" = $2 AND e."entityType" = \'FINDING\' AND e."status" = \'COMPLETED\' AND e."id" <> $1 AND e."vector" IS NOT NULL ORDER BY similarity DESC LIMIT $3', target.id, userId, Math.min(Math.max(limit, 1), 30))) as Array<{ sourceId: string; entityKey: string; contentPreview: string; url: string; title: string|null; similarity: number }>; }
export async function projectGraph(userId: string, projectId: string) { const project = await db.researchProject.findFirst({ where: { id: projectId, userId }, include: { sources: { include: { analyses: { where: { status: 'COMPLETED' }, orderBy: { createdAt: 'desc' }, take: 1 } } } } }); if (!project) throw new AIServiceError('PROVIDER_UNAVAILABLE', 'Project not found.'); const relationships = await db.researchRelationship.findMany({ where: { userId, projectId }, orderBy: { confidence: 'desc' }, take: 200 }); const nodes = project.sources.flatMap((source: any) => { const analysis = source.analyses[0]; const base = [{ id: `source:${source.id}`, type: 'SOURCE', label: source.title || source.domain || source.url, sourceId: source.id, url: source.url }]; const findings = asFindings(analysis?.keyFindings).slice(0, 5).map((finding: any, index: any) => ({ id: `finding:${analysis?.id}:${index}`, type: 'FINDING', label: finding.finding, sourceId: source.id, url: source.url })); return base.concat(findings); }); const edges = relationships.map((relationship: any) => ({ id: relationship.id, source: `${relationship.sourceEntity.toLowerCase()}:${relationship.sourceEntityKey}`, target: `${relationship.targetEntity.toLowerCase()}:${relationship.targetEntityKey}`, type: relationship.type, confidence: relationship.confidence, explanation: relationship.explanation })); return { nodes, edges }; }
export { SOURCE_THRESHOLD, FINDING_THRESHOLD, MAX_COMPARISONS };
