import { NextRequest, NextResponse } from 'next/server';
import { z } from 'zod';
import { db } from '@researchflow/database';
import { getCurrentUser } from '../../../../../lib/auth';
import { cleanText, idSchema, jsonError } from '../../../../../lib/api';
import { aiErrorResponse } from '../../../../../lib/ai/http';
import { answerResearchQuestion } from '../../../../../lib/ai/research-chat';
const questionSchema = z.object({ question: z.string().trim().min(3).max(4000) });
export async function GET(request: NextRequest, { params }: { params: { sessionId: string } }) { if (!idSchema.safeParse(params.sessionId).success) return jsonError('Invalid chat session ID.', 400); const user = await getCurrentUser(); if (!user) return jsonError('Authentication required.', 401); const limit = Math.min(Math.max(Number(request.nextUrl.searchParams.get('limit') || 50), 1), 100); const session = await db.chatSession.findFirst({ where: { id: params.sessionId, userId: user.id }, select: { id: true } }); if (!session) return jsonError('Chat session not found.', 404); const messages = await db.chatMessage.findMany({ where: { sessionId: session.id, userId: user.id }, orderBy: { createdAt: 'asc' }, take: limit, include: { citations: { orderBy: { citationOrder: 'asc' }, include: { source: { select: { id: true, title: true, url: true } }, researchItem: { select: { id: true, type: true } } } } } }); return NextResponse.json({ messages }); }
export async function POST(request: NextRequest, { params }: { params: { sessionId: string } }) { if (!idSchema.safeParse(params.sessionId).success) return jsonError('Invalid chat session ID.', 400); const user = await getCurrentUser(); if (!user) return jsonError('Authentication required.', 401); const parsed = questionSchema.safeParse(await request.json().catch(() => ({}))); if (!parsed.success) return jsonError('Enter a research question with at least 3 characters.', 400, parsed.error.flatten()); const session = await db.chatSession.findFirst({ where: { id: params.sessionId, userId: user.id }, select: { id: true } }); if (!session) return jsonError('Chat session not found.', 404); const question = cleanText(parsed.data.question, 4000); try { await db.chatMessage.create({ data: { userId: user.id, sessionId: session.id, role: 'USER', content: question } }); const result = await answerResearchQuestion(user.id, session.id, question); const assistant = await db.$transaction(async (tx) => { const message = await tx.chatMessage.create({ data: { userId: user.id, sessionId: session.id, role: 'ASSISTANT', content: result.output.answer, provider: result.provider, model: result.model, promptVersion: 'research-chat-v1', inputTokens: result.inputTokens, outputTokens: result.outputTokens } }); const validCitations = result.output.citations.map((citation, order) => ({ citation, result: result.results[citation.resultIndex], order })).filter((item) => item.result); if (validCitations.length) await tx.chatCitation.createMany({ data: validCitations.map(({ citation, result: evidence, order }) => ({ userId: user.id, messageId: message.id, sourceId: evidence.sourceId, researchItemId: evidence.entityType === 'RESEARCH_ITEM' ? evidence.entityKey : null, findingId: evidence.entityType === 'FINDING' ? evidence.entityKey : null, relevanceScore: evidence.relevance ?? evidence.similarity, citationOrder: order, reason: citation.reason })) }); await tx.usageCounter.upsert({ where: { userId_metric: { userId: user.id, metric: 'AI_CHAT_MESSAGES' } }, update: { count: { increment: 1 } }, create: { userId: user.id, metric: 'AI_CHAT_MESSAGES', count: 1 } }); return message; }); await db.chatSession.update({ where: { id: session.id }, data: { updatedAt: new Date() } }); return NextResponse.json({ message: { ...assistant, citations: result.output.citations.map((citation, order) => ({ ...citation, order, evidence: result.results[citation.resultIndex] })) }, evidence: result.results, insufficientEvidence: result.output.insufficientEvidence, confidence: result.output.confidence }); } catch (error) { return aiErrorResponse(error); } }
