import { NextResponse } from 'next/server';
import PDFDocument from 'pdfkit';
import { db } from '@researchflow/database';
import { getCurrentUser } from '../../../../../lib/auth';
import { idSchema, jsonError } from '../../../../../lib/api';
import { enforceLimit, recordUsage } from '../../../../../lib/billing/plan';
export const runtime = 'nodejs';
function pdfBuffer(title: string, projectTitle: string, content: string, references: string[]) { return new Promise<Buffer>((resolve, reject) => { const document = new PDFDocument({ margin: 54, size: 'A4' }); const chunks: Buffer[] = []; document.on('data', (chunk: Buffer) => chunks.push(chunk)); document.on('end', () => resolve(Buffer.concat(chunks))); document.on('error', reject); document.fillColor('#4f46e5').fontSize(11).text('RESEARCHFLOW', { characterSpacing: 1.5 }); document.moveDown(1); document.fillColor('#111827').fontSize(24).font('Helvetica-Bold').text(title); document.moveDown(0.4); document.font('Helvetica').fontSize(10).fillColor('#64748b').text(`Project: ${projectTitle}  •  Generated: ${new Date().toLocaleDateString()}`); document.moveDown(1.5); content.split(/\r?\n/).forEach((line) => { const trimmed = line.trim(); if (!trimmed) { document.moveDown(0.45); return; } if (trimmed.startsWith('# ')) document.font('Helvetica-Bold').fontSize(18).fillColor('#111827').text(trimmed.slice(2)); else if (trimmed.startsWith('## ')) document.moveDown(0.5).font('Helvetica-Bold').fontSize(14).fillColor('#1f2937').text(trimmed.slice(3)); else document.font('Helvetica').fontSize(10.5).fillColor('#334155').text(trimmed.replace(/\*\*/g, ''), { lineGap: 3 }); }); document.addPage(); document.font('Helvetica-Bold').fontSize(16).fillColor('#111827').text('References'); document.moveDown(); references.forEach((reference, index) => document.font('Helvetica').fontSize(10).fillColor('#334155').text(`[${index + 1}] ${reference}`, { lineGap: 5 })); document.end(); }); }
export async function GET(_request: Request, { params }: { params: { reportId: string } }) { if (!idSchema.safeParse(params.reportId).success) return jsonError('Invalid report ID.', 400); const user = await getCurrentUser(); if (!user) return jsonError('Authentication required.', 401); const report = await db.researchReport.findFirst({ where: { id: params.reportId, userId: user.id, status: 'COMPLETED' }, include: { project: { select: { title: true, sources: { select: { title: true, url: true } } } } } }); if (!report || !report.content) return jsonError('Completed report not found.', 404); try { await enforceLimit(user.id, 'exports', 'EXPORTS'); const references = report.project.sources.map((source: any) => `${source.title || 'Untitled source'} — ${source.url}`); const buffer = await pdfBuffer(report.title, report.project.title, report.content, references); await recordUsage(user.id, 'EXPORTS'); return new NextResponse(new Uint8Array(buffer), { headers: { 'Content-Type': 'application/pdf', 'Content-Disposition': `attachment; filename="${report.title.replace(/[^a-z0-9]+/gi, '-').toLowerCase()}.pdf"` } }); } catch (error) { return jsonError(error instanceof Error ? error.message : 'PDF export failed.', 429); } }
