import { NextRequest, NextResponse } from 'next/server';
import { z } from 'zod';
import { db } from '@researchflow/database';
import { getCurrentUser } from '../../../../lib/auth';
import { cleanText, idSchema, jsonError, paged, paginationFrom } from '../../../../lib/api';

const schema = z.object({ type: z.enum(['PAGE', 'PAGE_CONTENT', 'SELECTION', 'NOTE']), content: z.string().trim().min(1).max(200_000) });
async function ownedSource(sourceId: string) { const user = await getCurrentUser(); if (!user) return { error: jsonError('Authentication required.', 401) }; if (!idSchema.safeParse(sourceId).success) return { error: jsonError('Invalid source ID.', 400) }; const source = await db.source.findFirst({ where: { id: sourceId, project: { userId: user.id } }, select: { id: true } }); if (!source) return { error: jsonError('Source not found.', 404) }; return { user, source }; }
export async function GET(request: NextRequest, { params }: { params: { sourceId: string } }) { try { const result = await ownedSource(params.sourceId); if (result.error) return result.error; const { page, limit } = paginationFrom(request); const [items, total] = await db.$transaction([db.researchItem.findMany({ where: { sourceId: result.source.id }, orderBy: { createdAt: 'desc' }, skip: (page - 1) * limit, take: limit }), db.researchItem.count({ where: { sourceId: result.source.id } })]); return NextResponse.json(paged(items, page, limit, total)); } catch { return jsonError('The research-item service is unavailable.', 503); } }
export async function POST(request: NextRequest, { params }: { params: { sourceId: string } }) { const parsed = schema.safeParse(await request.json().catch(() => null)); if (!parsed.success) return jsonError('Invalid research item data.', 400, parsed.error.flatten()); try { const result = await ownedSource(params.sourceId); if (result.error) return result.error; const content = cleanText(parsed.data.content); const duplicate = parsed.data.type === 'SELECTION' ? await db.researchItem.findFirst({ where: { sourceId: result.source.id, type: 'SELECTION', content } }) : null; if (duplicate) return NextResponse.json({ error: 'This selected insight already exists.', code: 'DUPLICATE_ITEM', existingItemId: duplicate.id }, { status: 409 }); return NextResponse.json(await db.researchItem.create({ data: { sourceId: result.source.id, type: parsed.data.type, content } }), { status: 201 }); } catch { return jsonError('The research item could not be saved.', 503); } }
