import { NextRequest, NextResponse } from 'next/server';
import { z } from 'zod';
import { db } from '@researchflow/database';
import { getCurrentUser } from '../../lib/auth';
import { jsonError } from '../../lib/api';
import { aiErrorResponse } from '../../lib/ai/http';
import { generateReport } from '../../lib/reports/service';
import { enforceLimit, recordUsage } from '../../lib/billing/plan';
const schema = z.object({ projectId: z.string(), title: z.string().trim().min(1).max(200).optional() });
export async function GET(request: NextRequest) { const user = await getCurrentUser(); if (!user) return jsonError('Authentication required.', 401); const projectId = request.nextUrl.searchParams.get('projectId') ?? undefined; return NextResponse.json({ reports: await db.researchReport.findMany({ where: { userId: user.id, projectId }, orderBy: { updatedAt: 'desc' }, take: 50, select: { id: true, projectId: true, title: true, status: true, format: true, generatedAt: true, updatedAt: true } }) }); }
export async function POST(request: NextRequest) { const parsed = schema.safeParse(await request.json().catch(() => ({}))); if (!parsed.success) return jsonError('A project is required to generate a report.', 400, parsed.error.flatten()); const user = await getCurrentUser(); if (!user) return jsonError('Authentication required.', 401); let reportId: string | undefined; try { await enforceLimit(user.id, 'reports', 'REPORTS'); const project = await db.researchProject.findFirst({ where: { id: parsed.data.projectId, userId: user.id }, select: { id: true, title: true } }); if (!project) return jsonError('Project not found.', 404); const report = await db.researchReport.create({ data: { userId: user.id, projectId: project.id, title: parsed.data.title ?? `${project.title} Research Report`, status: 'PROCESSING' } }); reportId = report.id; const result = await generateReport(user.id, project.id, report.title); const completed = await db.researchReport.update({ where: { id: report.id }, data: { title: result.title, content: result.content, provider: result.provider, model: result.model, status: 'COMPLETED', format: 'MARKDOWN', generatedAt: new Date(), errorMessage: null } }); await recordUsage(user.id, 'REPORTS'); return NextResponse.json({ report: completed }, { status: 201 }); } catch (error) { if (reportId) await db.researchReport.update({ where: { id: reportId }, data: { status: 'FAILED', errorMessage: error instanceof Error ? error.message : 'Report generation failed.' } }).catch(() => undefined); return aiErrorResponse(error); } }
