import { db } from '@researchflow/database';
import { AIServiceError } from '../ai/types';
const numberEnv = (name: string, fallback: number) => { const value = Number(process.env[name]); return Number.isFinite(value) && value >= 0 ? value : fallback; };
export const PLAN_LIMITS = { FREE: { projects: 2, sources: 30, analyses: 20, chatMessages: 30, reports: numberEnv('FREE_REPORT_LIMIT', 3), exports: numberEnv('FREE_EXPORT_LIMIT', 6) }, PRO: { projects: Number.POSITIVE_INFINITY, sources: 1000, analyses: 500, chatMessages: 500, reports: numberEnv('PRO_REPORT_LIMIT', 100), exports: numberEnv('PRO_EXPORT_LIMIT', 200) } } as const;
export type LimitKey = keyof typeof PLAN_LIMITS.FREE;
export async function currentPlan(userId: string) { const subscription = await db.subscription.findUnique({ where: { userId }, select: { plan: true, status: true } }); return subscription?.status === 'ACTIVE' || subscription?.status === 'TRIALING' ? subscription.plan : (await db.user.findUnique({ where: { id: userId }, select: { plan: true } }))?.plan ?? 'FREE'; }
function period() { const start = new Date(); start.setUTCDate(1); start.setUTCHours(0, 0, 0, 0); const end = new Date(start); end.setUTCMonth(end.getUTCMonth() + 1); return { start, end }; }
export async function usageFor(userId: string, feature: 'REPORTS'|'EXPORTS'|'AI_CHAT_MESSAGES') { const { start } = period(); return db.usageRecord.findUnique({ where: { userId_feature_periodStart: { userId, feature, periodStart: start } }, select: { count: true } }); }
export async function enforceLimit(userId: string, key: LimitKey, feature: 'REPORTS'|'EXPORTS'|'AI_CHAT_MESSAGES') { const plan = await currentPlan(userId); const limit = PLAN_LIMITS[plan][key]; const usage = await usageFor(userId, feature); if (usage && usage.count >= limit) throw new AIServiceError('RATE_LIMIT', `You have reached the ${plan === 'FREE' ? 'Free' : 'current'} plan limit for this feature.`, false); return { plan, limit, used: usage?.count ?? 0 }; }
export async function recordUsage(userId: string, feature: 'REPORTS'|'EXPORTS'|'AI_CHAT_MESSAGES') { const { start, end } = period(); return db.usageRecord.upsert({ where: { userId_feature_periodStart: { userId, feature, periodStart: start } }, update: { count: { increment: 1 } }, create: { userId, feature, count: 1, periodStart: start, periodEnd: end } }); }
export const paymentProviderContract = { checkout: 'Future provider creates a server-verified checkout session.', webhook: 'Future provider verifies signed webhook events before updating Subscription.' } as const;
