import { NextRequest, NextResponse } from 'next/server';
import { z } from 'zod';
import { db } from '@researchflow/database';
import { getCurrentUser } from '../../../lib/auth';
import { cleanText, idSchema, jsonError } from '../../../lib/api';

const updateSchema = z.object({ title: z.string().trim().max(500).nullable().optional(), description: z.string().trim().max(5000).nullable().optional(), author: z.string().trim().max(255).nullable().optional(), faviconUrl: z.string().url().max(2048).nullable().optional(), publishedAt: z.string().datetime().nullable().optional() }).refine((value) => Object.keys(value).length > 0, 'At least one field is required.');
async function ownedSource(sourceId: string) { const parsed = idSchema.safeParse(sourceId); if (!parsed.success) return { error: jsonError('Invalid source ID.', 400) }; const user = await getCurrentUser(); if (!user) return { error: jsonError('Authentication required.', 401) }; const source = await db.source.findFirst({ where: { id: sourceId, project: { userId: user.id } } }); if (!source) return { error: jsonError('Source not found.', 404) }; return { user, source }; }
export async function GET(_request: NextRequest, { params }: { params: { sourceId: string } }) { try { const result = await ownedSource(params.sourceId); if (result.error) return result.error; return NextResponse.json(await db.source.findUnique({ where: { id: result.source.id }, include: { items: true, project: { select: { id: true, title: true } } } })); } catch { return jsonError('The source service is unavailable.', 503); } }
export async function PATCH(request: NextRequest, { params }: { params: { sourceId: string } }) { const parsed = updateSchema.safeParse(await request.json().catch(() => null)); if (!parsed.success) return jsonError('Invalid source data.', 400, parsed.error.flatten()); try { const result = await ownedSource(params.sourceId); if (result.error) return result.error; const data = { ...parsed.data, title: parsed.data.title ? cleanText(parsed.data.title, 500) : parsed.data.title, description: parsed.data.description ? cleanText(parsed.data.description, 5000) : parsed.data.description, author: parsed.data.author ? cleanText(parsed.data.author, 255) : parsed.data.author, publishedAt: parsed.data.publishedAt === undefined ? undefined : parsed.data.publishedAt ? new Date(parsed.data.publishedAt) : null }; return NextResponse.json(await db.source.update({ where: { id: result.source.id }, data })); } catch { return jsonError('The source could not be updated.', 503); } }
export async function DELETE(_request: NextRequest, { params }: { params: { sourceId: string } }) { try { const result = await ownedSource(params.sourceId); if (result.error) return result.error; await db.source.delete({ where: { id: result.source.id } }); return new NextResponse(null, { status: 204 }); } catch { return jsonError('The source could not be deleted.', 503); } }
