import { db } from '@researchflow/database';
import type { AIAnalysisView, AIKeyFinding } from '@researchflow/shared';
import { AnalysisPanel } from '../../../../components/analysis-panel';
import { getCurrentUser } from '../../../../lib/auth';

type SourcePageProps = { params: { projectId: string; sourceId: string } };
async function getSource(projectId: string, sourceId: string) { const user = await getCurrentUser(); if (!user) return null; return db.source.findFirst({ where: { id: sourceId, projectId, project: { userId: user.id } }, include: { items: true, analyses: { orderBy: { createdAt: 'desc' }, take: 1 } } }); }
function analysisView(value: NonNullable<Awaited<ReturnType<typeof getSource>>>['analyses'][number]): AIAnalysisView { const strings = (input: unknown) => Array.isArray(input) ? input.filter((item): item is string => typeof item === 'string') : []; const findings = (input: unknown) => Array.isArray(input) ? input.filter((item): item is AIKeyFinding => typeof item === 'object' && item !== null && 'finding' in item && 'importance' in item && typeof item.finding === 'string' && (item.importance === 'high' || item.importance === 'medium' || item.importance === 'low')) : []; return { id: value.id, sourceId: value.sourceId, researchItemId: value.researchItemId, summary: value.summary, keyPoints: strings(value.keyPoints), keyFindings: findings(value.keyFindings), keywords: strings(value.keywords), topics: strings(value.topics), contentType: value.contentType, provider: value.provider, model: value.model, promptVersion: value.promptVersion, status: value.status, errorMessage: value.errorMessage, attemptCount: value.attemptCount, createdAt: value.createdAt.toISOString(), updatedAt: value.updatedAt.toISOString(), completedAt: value.completedAt?.toISOString() ?? null }; }
export default async function SourcePage({ params }: SourcePageProps) { const source = await getSource(params.projectId, params.sourceId); if (!source) return <main className="grid min-h-screen place-items-center p-6"><div className="rounded-xl border bg-white p-8 text-center"><h1 className="text-xl font-semibold">Source not found</h1><p className="mt-2 text-sm text-slate-500">Sign in or check that this source belongs to your project.</p></div></main>; const latest = source.analyses[0] ? analysisView(source.analyses[0]) : null; return <main className="min-h-screen bg-slate-50 p-6 md:p-12"><article className="mx-auto max-w-3xl rounded-2xl border border-slate-200 bg-white p-7 shadow-sm"><a className="text-sm font-medium text-indigo-600" href="/">← ResearchFlow dashboard</a><p className="mt-8 text-sm text-slate-500">{source.domain ?? source.url}</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">{source.title ?? 'Untitled source'}</h1><a className="mt-3 block break-all text-sm text-indigo-600" href={source.url} target="_blank" rel="noreferrer">{source.url}</a><p className="mt-6 text-xs uppercase tracking-wider text-slate-400">Captured {new Date(source.capturedAt).toLocaleString()}</p><div className="mt-8 space-y-6">{source.items.map((item: any) => <section key={item.id}><div className="mb-2 text-xs font-semibold uppercase tracking-wider text-indigo-600">{item.type === 'SELECTION' ? 'Selected insight' : 'Page content'}</div><p className="whitespace-pre-wrap text-sm leading-7 text-slate-700">{item.content}</p></section>)}</div><AnalysisPanel sourceId={source.id} initialAnalysis={latest} /></article></main> }
