import { NextRequest, NextResponse } from 'next/server';
import { z } from 'zod';
import { db } from '@researchflow/database';
import { getCurrentUser } from '../../../../lib/auth';
import { idSchema, jsonError } from '../../../../lib/api';
const patchSchema = z.object({ title: z.string().trim().min(1).max(120) });
async function owned(userId: string, sessionId: string) { return db.chatSession.findFirst({ where: { id: sessionId, userId }, include: { messages: { orderBy: { createdAt: 'asc' }, take: 100, include: { citations: { orderBy: { citationOrder: 'asc' }, include: { source: { select: { id: true, title: true, url: true } }, researchItem: { select: { id: true, type: true } } } } } } } }); }
export async function GET(_request: Request, { params }: { params: { sessionId: string } }) { if (!idSchema.safeParse(params.sessionId).success) return jsonError('Invalid chat session ID.', 400); const user = await getCurrentUser(); if (!user) return jsonError('Authentication required.', 401); const session = await owned(user.id, params.sessionId); if (!session) return jsonError('Chat session not found.', 404); return NextResponse.json({ session }); }
export async function PATCH(request: NextRequest, { params }: { params: { sessionId: string } }) { if (!idSchema.safeParse(params.sessionId).success) return jsonError('Invalid chat session ID.', 400); const user = await getCurrentUser(); if (!user) return jsonError('Authentication required.', 401); const parsed = patchSchema.safeParse(await request.json().catch(() => ({}))); if (!parsed.success) return jsonError('Invalid chat title.', 400, parsed.error.flatten()); const session = await db.chatSession.findFirst({ where: { id: params.sessionId, userId: user.id }, select: { id: true } }); if (!session) return jsonError('Chat session not found.', 404); return NextResponse.json({ session: await db.chatSession.update({ where: { id: session.id }, data: { title: parsed.data.title } }) }); }
export async function DELETE(_request: Request, { params }: { params: { sessionId: string } }) { if (!idSchema.safeParse(params.sessionId).success) return jsonError('Invalid chat session ID.', 400); const user = await getCurrentUser(); if (!user) return jsonError('Authentication required.', 401); const result = await db.chatSession.deleteMany({ where: { id: params.sessionId, userId: user.id } }); if (!result.count) return jsonError('Chat session not found.', 404); return new NextResponse(null, { status: 204 }); }
