import { NextRequest, NextResponse } from 'next/server';
import { z } from 'zod';
import { db } from '@researchflow/database';
import { getCurrentUser } from '../../../lib/auth';
import { idSchema, jsonError } from '../../../lib/api';
const schema = z.object({ title: z.string().trim().min(1).max(200).optional(), content: z.string().trim().min(1).max(50000).optional() }).refine((value) => value.title !== undefined || value.content !== undefined);
export async function GET(_request: Request, { params }: { params: { reportId: string } }) { if (!idSchema.safeParse(params.reportId).success) return jsonError('Invalid report ID.', 400); const user = await getCurrentUser(); if (!user) return jsonError('Authentication required.', 401); const report = await db.researchReport.findFirst({ where: { id: params.reportId, userId: user.id }, include: { project: { select: { id: true, title: true } } } }); if (!report) return jsonError('Report not found.', 404); return NextResponse.json({ report }); }
export async function PATCH(request: NextRequest, { params }: { params: { reportId: string } }) { if (!idSchema.safeParse(params.reportId).success) return jsonError('Invalid report ID.', 400); const user = await getCurrentUser(); if (!user) return jsonError('Authentication required.', 401); const parsed = schema.safeParse(await request.json().catch(() => ({}))); if (!parsed.success) return jsonError('Provide a report title or content.', 400, parsed.error.flatten()); const existing = await db.researchReport.findFirst({ where: { id: params.reportId, userId: user.id }, select: { id: true, status: true } }); if (!existing) return jsonError('Report not found.', 404); return NextResponse.json({ report: await db.researchReport.update({ where: { id: existing.id }, data: { ...parsed.data, format: 'MARKDOWN' } }) }); }
export async function DELETE(_request: Request, { params }: { params: { reportId: string } }) { if (!idSchema.safeParse(params.reportId).success) return jsonError('Invalid report ID.', 400); const user = await getCurrentUser(); if (!user) return jsonError('Authentication required.', 401); const result = await db.researchReport.deleteMany({ where: { id: params.reportId, userId: user.id } }); if (!result.count) return jsonError('Report not found.', 404); return new NextResponse(null, { status: 204 }); }
